project:
  type: website

website:
  title: "Home"
  site-url: https://jhylin.github.io/Data_in_life_blog/
  description: "A blog website about using software tools to decipher drug discovery and development data"
  page-footer: "Website made with ðŸ’œ in [Quarto](https://quarto.org/) by Jennifer HY Lin Â© 2022 - 2025"
  google-analytics: "G-5CHVP3K63C"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - text: "{{< fa brands bluesky >}}"
        href: https://bsky.app/profile/jhylin.bsky.social
      - icon: mastodon
        href: https://fosstodon.org/@jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
      - icon: linkedin
        href: https://www.linkedin.com/in/jennifer-hy-lin-a9b86981/
      - text: CV
        href: https://jhylin.github.io/CV_resume_quarto/
      - icon: rss
        href: index.xml
  repo-url: https://github.com/jhylin/Data_in_life_blog
  repo-actions: [issue]
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    

editor: visual

comments:
  giscus:
    repo: jhylin/Data_in_life_blog