project:
  type: website

website:
  title: "Home"
  page-footer: "Blog made with ‚ù§Ô∏è in [Quarto](https://quarto.org/) by Jennifer HY Lin ¬© 2022 üìï Citation as author and blog URL link if used"
  google-analytics: "G-5CHVP3K63C"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jhylin
      - icon: twitter
        href: https://twitter.com/jenhylin
      - text: Resume
        href: https://jhylin.github.io/CV_resume_quarto/index.pdf
  repo-url: https://github.com/jhylin/Data_in_life_blog
  repo-actions: [issue]
    
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    

editor: visual

comments:
  giscus:
    repo: jhylin/Data_in_life_blog